version: '3.8'

services:
  app:
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env.production
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

networks:
  app-network:
    driver: bridge